#!/bin/bash

################################################################################################
### sbatch configuration parameters must start with #SBATCH and must precede any other commands.
### To ignore, just add another # - like so: ##SBATCH
################################################################################################

#SBATCH --partition main			### specify partition name where to run a job. change only if you have a matching qos!! main: all nodes; gtx1080: 1080 gpu card nodes; rtx2080: 2080 nodes; teslap100: p100 nodes; titanrtx: titan nodes
#SBATCH --time 0-96:00:00			### limit the time of job running. Make sure it is not greater than the partition time limit!! Format: D-H:MM:SS
#SBATCH --job-name aleph_bert_train			### name of the job
#SBATCH --output job-%J.out			### output log for running job - %J for job number
#SBATCH --gpus=rtx_6000:1				### number of GPUs, allocating more than 1 requires IT team's permission. Example to request 3090 gpu: #SBATCH --gpus=rtx_3090:1

# Note: the following 4 lines are commented out
##SBATCH --mail-user=user@post.bgu.ac.il	### user's email for sending job status messages
##SBATCH --mail-type=ALL			### conditions for sending the email. ALL,BEGIN,END,FAIL, REQUEU, NONE
##SBATCH --mem=24G				### ammount of RAM memory, allocating more than 60G requires IT team's permission

################  Following lines will be executed by a compute node    #######################

### Print some data to output file ###
#echo `date`
#echo -e "\nSLURM_JOBID:\t\t" $SLURM_JOBID
#echo -e "SLURM_JOB_NODELIST:\t" $SLURM_JOB_NODELIST "\n\n"

### Start your code below ####
module load anaconda				### load anaconda module (must be present when working with conda environments)
source activate alephbert_eval				### activate a conda environment, replace my_env with your conda environment
python -m hebrew_summarizer.cli \
    --model_name_or_path "imvladikon/het5_small_summarization" \
    --do_train \
    --do_eval \
    --train_file "trainDatasets/summeries_train.csv" \
    --validation_file "trainDatasets/summeries_eval.csv" \
    --output_dir "finetuned_het5" \
    --text_column "text" \
    --num_train_epochs 30 \
    --summary_column "summary" \
    --per_device_train_batch_size=8 \
    --per_device_eval_batch_size=8 \
    --overwrite_output_dir \
    --predict_with_generate \
    --load_best_model_at_end \
    --save_total_limit 2 \
    --save_strategy "epoch" \
    --eval_strategy "epoch" 

